### ISSUE TITLE
The npm install doesnt work

### ISSUE THREAD

**Issue by susnas** [ionicthemes/build-a-complete-mobile-app-with-ionic-framework#1]
After downloading the code when i tried to install the dependencies there is an error comes like 

Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-02-23T06_19_29_334Z-debug.log
I am new to ionic and cannot handle with this error even if i used the npm clean --force.

**Comment by xbass540** [comment]
I also have this problem. I found some useful info [here](https://stackoverflow.com/questions/48298361/npm-install-failed-at-the-node-sass4-5-0-postinstall-script#48298933) but i am not keen to uninstall all dependencies and downgrade them to older versions to make this work. Did @susnas find any solution to this?

**Comment by djabif** [comment]
New version has been released. Everything should work now :)
